name: NuGet Packages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/NuGetPackages.yml'
      - 'src/NuGetPackages/Saascade.Blazor.Components/**'
    tags:
      - 'v*'   # trigger on version tags like v1.0.0
  workflow_dispatch:
    inputs:
        version:
          description: 'Package version'
          required: true
          default: '0.0.0.1'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '10.0.x'
 
      - name: Generate version
        id: version
        run: |
          DATE=$(date -u +'%Y%m%d%H%M')
          SHA=${GITHUB_SHA::7}
          VERSION="0.0.0-${DATE}.${SHA}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: List folder for debugging
        run: find . -type d
   
      # 📦 Restore everything
      - name: Restore
        run: dotnet restore
        working-directory: ./src/NuGetPackages

      # 🔨 Build everything
      - name: Build 
        run: dotnet build --configuration Release --no-restore
        working-directory: ./src/NuGetPackages


      # 📦 Pack everything
      - name: Pack - Saascade.Blazor.Components
        working-directory: ./src/NuGetPackages/Saascade.Blazor.Components
        run: |
          dotnet pack --configuration Release \
            /p:PackageVersion=${{ steps.version.outputs.VERSION }} \
            --output ../../nupkgs

#      - name: Pack - Saascade.Blazor.Components
#        working-directory: ./src/Saascade.Blazor.Components
#        run: |
#          dotnet pack --configuration Release \
#            /p:PackageVersion=${{ steps.version.outputs.VERSION }} \
#            --output ../../nupkgs
#
#      - name: Pack - Saascade.Blazor.DesignSystems
#        working-directory: ./src/Saascade.Blazor.DesignSystems
#        run: |
#          dotnet pack --configuration Release \
#            /p:PackageVersion=${{ steps.version.outputs.VERSION }} \
#            --output ../../nupkgs
      # 📦 Pack all projects
      - name: Pack all projects
        run: |
          mkdir -p nupkgs
          for proj in $(find . -name "*.csproj"); do
            echo "Packing $proj"
            dotnet pack "$proj" \
              --configuration Release \
              --no-build \
              /p:PackageVersion=${{ steps.version.outputs.VERSION }} \
              --output ./nupkgs
          done
        working-directory: ./src/NuGetPackages
        
      - name: List packages
        run: ls -R nupkgs

      # 🚀 Push all packages 
      - name: Push packages
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --skip-duplicate

      # TODO: Could be useful in future
#       # 📦 Pack all projects
#       - name: Pack all projects
#         run: |
#           mkdir -p nupkgs
#           for proj in $(find . -name "*.csproj"); do
#             echo "Packing $proj"
#             dotnet pack "$proj" \
#               --configuration Release \
#               --no-build \
#               /p:PackageVersion=${{ steps.version.outputs.VERSION }} \
#               --output ./nupkgs
#           done
#         working-directory: ./src 
      
      # - name: Publish packages
      #   run: dotnet nuget push "./nupkgs/*.nupkg" \
      #         --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
      #         --api-key ${{ secrets.GITHUB_TOKEN }} \
      #         --skip-duplicate
      #   working-directory: ./src
