name: Publish NuGet Package


on:
  push:
    branches:
      - main
    paths:
      - 'src/Saascade.Blazor.Components/**' 
      - '.github/workflows/publish-nuget-package.yml'
    # tags:
    #   - 'v*'   # trigger on version tags like v1.0.0
  workflow_dispatch:
    inputs:
        version:
          description: 'Package version'
          required: true
          default: '0.0.0.1'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        working-directory: ./src/Saascade.Blazor.Components
        run: dotnet restore
 
      - name: Generate version
        id: version
        run: |
          DATE=$(date -u +'%Y%m%d%H%M')
          SHA=${GITHUB_SHA::7}
          VERSION="0.0.0.${DATE}.${SHA}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build
        working-directory: ./src/Saascade.Blazor.Components
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        working-directory: ./src/Saascade.Blazor.Components
        run: |
          dotnet pack --configuration Release \
            /p:PackageVersion=${{ steps.version.outputs.VERSION }} \
            --output ../../nupkgs

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GITHUB_TOKEN }}